[package]
name = "circle_progress_bar"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
relm4 = "0.7.0-alpha.1"
anyhow = "1.0.75"
